### ISSUE TITLE
images as attachments not accessible via HTTP from couchbase-lite

### ISSUE THREAD

**Issue by ssomnoremac** [InfiniteLibrary/infinite-reader#1]
For a truly offline experience, thumbnail images should be locally as attachments on couchbase-lite. Problem is the that the couchbaselite server on the device localhost:5984/images/cover.jpg for example does not seem to work as a source target for the Image source attribute.

**Comment by ssomnoremac** [comment]
bug is being tracked [here](https://github.com/fraserxu/react-native-couchbase-lite/issues/11)

**Comment by louisruch** [comment]
Issue resolved with #16
