### ISSUE TITLE
Add HTML book to WebView as reader

### ISSUE THREAD

**Issue by ssomnoremac** [InfiniteLibrary/infinite-reader#18]
One step at a time. Let's not try and save htmlbooks yet. Let's just try and pull htmlbooks from [infinitelibrarylibary](https://github.com/InfiniteLibraryLibrary) and show the correct book loaded when "read" is clicked.

**Comment by ssomnoremac** [comment]
@sandersk what's the entry point each of the htmlbooks? Can you not just use them as hosted on github to start reading? Are they served anywhere already?

**Comment by ssomnoremac** [comment]
oh, wait I found it:  
 `var bookURL ="https://rawgit.com/InfiniteLibraryLibrary/Middlemarch_145/master/book.xhtml"`

based on [this guide it should be different in production](https://rawgit.com/)

**Comment by sandersk** [comment]
Yup, the HTMLBook files are named book.xhtml at the root of each repo.

**Comment by ssomnoremac** [comment]
Thanks, awesome, it works. This is closed and merged with #19.
